Repository DSM-DECONHUB/deconhub-server, pull requests merged in 2022-10, with the labels that each got.

#5 2. signup
  .idea/workspace.xml
  build.gradle
  src/main/java/com/example/deconhubserver/domain/user/controller/UserController.java
  src/main/java/com/example/deconhubserver/domain/user/dto/LoginRequest.java
  src/main/java/com/example/deconhubserver/domain/user/dto/SignupRequest.java
  src/main/java/com/example/deconhubserver/domain/user/dto/UserResponse.java
  src/main/java/com/example/deconhubserver/domain/user/entity/User.java
  src/main/java/com/example/deconhubserver/domain/user/enums/Role.java
  src/main/java/com/example/deconhubserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/security/auth/AuthDetails.java
  src/main/java/com/example/deconhubserver/global/security/auth/AuthDetailsService.java
  src/main/java/com/example/deconhubserver/global/security/config/JpaConfig.java
  src/main/java/com/example/deconhubserver/global/security/config/RedisConfig.java
  src/main/java/com/example/deconhubserver/global/security/config/SecurityConfig.java
  src/main/java/com/example/deconhubserver/global/security/config/SwaggerConfig.java
  src/main/java/com/example/deconhubserver/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/deconhubserver/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/deconhubserver/global/security/jwt/dao/RedisDao.java
  src/main/java/com/example/deconhubserver/global/security/jwt/dto/TokenResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 기능 추가

#8 🔀 :: (#7) exception setting
  src/main/java/com/example/deconhubserver/domain/auth/exception/PasswordMissMatchedException.java
  src/main/java/com/example/deconhubserver/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/example/deconhubserver/domain/user/exception/UserNotFoundException.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/config/FilterConfig.java
  src/main/java/com/example/deconhubserver/global/config/JpaConfig.java
  src/main/java/com/example/deconhubserver/global/config/RedisConfig.java
  src/main/java/com/example/deconhubserver/global/config/SecurityConfig.java
  src/main/java/com/example/deconhubserver/global/config/SwaggerConfig.java
  src/main/java/com/example/deconhubserver/global/config/WebConfig.java
  src/main/java/com/example/deconhubserver/global/error/ErrorCode.java
  src/main/java/com/example/deconhubserver/global/error/ErrorResponse.java
  src/main/java/com/example/deconhubserver/global/error/exception/CustomException.java
  src/main/java/com/example/deconhubserver/global/error/exception/ExceptionFilter.java
  src/main/java/com/example/deconhubserver/global/error/exception/GlobalExceptionHandler.java
  src/main/java/com/example/deconhubserver/global/filter/JwtAuthenticationFilter.java
Labels: 기능 추가, 리팩토링, 기능 수정

#10 #9 refresh token change
  .idea/workspace.xml
  src/main/java/com/example/deconhubserver/domain/user/exception/RoleNotFoundException.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/error/ErrorCode.java
  src/main/java/com/example/deconhubserver/global/exception/JwtExpiredException.java
  src/main/java/com/example/deconhubserver/global/exception/JwtInvalidException.java
  src/main/java/com/example/deconhubserver/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/deconhubserver/global/security/jwt/dao/RedisDao.java
  src/main/java/com/example/deconhubserver/global/security/jwt/entity/RefreshToken.java
  src/main/java/com/example/deconhubserver/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/resources/application.yml
Labels: 기능 수정

#12 #11signup pw valid
  src/main/java/com/example/deconhubserver/domain/user/dto/SignupRequest.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/config/SecurityConfig.java
Labels: 기능 수정

#15 🔀 :: (#14) query myinfo
  src/main/java/com/example/deconhubserver/domain/user/controller/UserController.java
  src/main/java/com/example/deconhubserver/domain/user/dto/MyInfoResponse.java
  src/main/java/com/example/deconhubserver/domain/user/facade/UserFacade.java
  src/main/java/com/example/deconhubserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/config/SecurityConfig.java
  src/main/java/com/example/deconhubserver/global/config/SwaggerConfig.java
  src/main/java/com/example/deconhubserver/global/mail/service/MailService.java
  src/main/java/com/example/deconhubserver/global/security/auth/AuthDetailsService.java
  src/main/java/com/example/deconhubserver/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#19 🔀 :: (#17) image upload
  build.gradle
  src/main/java/com/example/deconhubserver/domain/image/controller/ImageController.java
  src/main/java/com/example/deconhubserver/domain/image/dto/ImageListResponse.java
  src/main/java/com/example/deconhubserver/domain/image/service/ImageService.java
  src/main/java/com/example/deconhubserver/domain/user/controller/UserController.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/error/ErrorCode.java
  src/main/java/com/example/deconhubserver/infrastucture/mail/dto/MailRequest.java
  src/main/java/com/example/deconhubserver/infrastucture/mail/service/MailService.java
  src/main/java/com/example/deconhubserver/infrastucture/s3/DefaultImage.java
  src/main/java/com/example/deconhubserver/infrastucture/s3/ImageUtil.java
  src/main/java/com/example/deconhubserver/infrastucture/s3/exception/ImageNotFoundException.java
  src/main/java/com/example/deconhubserver/infrastucture/s3/exception/InvalidImageExtensionFormatException.java
  src/main/java/com/example/deconhubserver/infrastucture/s3/facade/ImageFacade.java
  src/main/resources/application.yml
Labels: 기능 추가

#18 🔀 :: (#13) contest Crud
  .idea/workspace.xml
  src/main/java/com/example/deconhubserver/domain/contest/controller/ContestController.java
  src/main/java/com/example/deconhubserver/domain/contest/dto/ContestList.java
  src/main/java/com/example/deconhubserver/domain/contest/dto/ContestRequest.java
  src/main/java/com/example/deconhubserver/domain/contest/dto/ContestResponse.java
  src/main/java/com/example/deconhubserver/domain/contest/entity/Contest.java
  src/main/java/com/example/deconhubserver/domain/contest/enums/ContestCategory.java
  src/main/java/com/example/deconhubserver/domain/contest/exception/UserMissMatchedException.java
  src/main/java/com/example/deconhubserver/domain/contest/facade/ContestFacade.java
  src/main/java/com/example/deconhubserver/domain/contest/repository/ContestRepository.java
  src/main/java/com/example/deconhubserver/domain/contest/service/ContestService.java
  src/main/java/com/example/deconhubserver/domain/user/entity/User.java
  src/main/java/com/example/deconhubserver/domain/user/exception/ContestNotFoundException.java
  src/main/java/com/example/deconhubserver/domain/user/service/UserService.java
  src/main/java/com/example/deconhubserver/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: 기능 추가

#20 🔀 :: (#16) question post get
  src/main/java/com/example/deconhubserver/domain/question/controller/QuestionController.java
  src/main/java/com/example/deconhubserver/domain/question/dto/QuestionList.java
  src/main/java/com/example/deconhubserver/domain/question/dto/QuestionRequest.java
  src/main/java/com/example/deconhubserver/domain/question/dto/QuestionResponse.java
  src/main/java/com/example/deconhubserver/domain/question/entity/Question.java
  src/main/java/com/example/deconhubserver/domain/question/exception/QuestionNotFoundException.java
  src/main/java/com/example/deconhubserver/domain/question/facade/QuestionFacade.java
  src/main/java/com/example/deconhubserver/domain/question/repository/QuestionRepository.java
  src/main/java/com/example/deconhubserver/domain/question/service/QuestionService.java
  src/main/java/com/example/deconhubserver/domain/user/entity/User.java
  src/main/resources/application.yml
Labels: 기능 추가
